Toggle for Status Display to Always Show as Text
RSCPlus/rscplus pull request #136
Opened 2023-02-18 16:49 UTC by 15rtrujillo

Added a toggle to have the HP/Prayer/Fatigue display always show as text instead of bars.

2023-02-18 17:04 UTC, conker-rsc requested changes

2023-02-18 17:07 UTC, 15rtrujillo commented on src/Game/Renderer.java
> +        if (!roomInHbarForHPPrayerFatigueOverlay() || Settings.ALWAYS_SHOW_HP_PRAYER_FATIGUE_AS_TEXT.get(Settings.currentProfile)) {
Good point lol

2023-02-18 17:07 UTC, 15rtrujillo commented on src/Client/Settings.java
> +  public static void toggleHpPrayerFatigueOverlayAlwaysText() {
Lol I just was kinda copying everything that the SHOW_HP_PRAYER_FATIGUE_OVERLAY setting did. I didn't even notice that I didn't end up using that function. Guess that's what I get for taking a 3 or 4 day break in the middle of putting this in.

2023-03-09 04:29 UTC, Hubcapp approved these changes
good enough, thanks Ryan! :-)

2023-03-09 04:30 UTC, merged