Worldmap
RSCPlus/rscplus pull request #82
Opened 2021-03-01 02:04 UTC by OrN

Adds a world map that can be accessed via clicking Map icon, or pressing alt + m. Also introduces some changes to login message and settings having a button on the wrench.

The map can do a lot of things, waypoints, searching, object searching, hightlighting, tracking player position.

Needs some testing.

2021-03-01 02:14 UTC, Hubcapp requested changes

2021-03-01 02:14 UTC, Hubcapp commented on src/Client/WorldMapWindow.java
> +        System.out.println("update");
oops

2021-03-01 02:14 UTC, Hubcapp commented on src/Client/WorldMapWindow.java
> +                    "There was a thread-related error while setting up the replay queue window! The window may not be initialized properly!");
this is not the replay queue window

2021-03-01 02:14 UTC, Hubcapp commented on src/Client/WorldMapWindow.java
> +            Logger.Error("There was a thread-related error while setting up the replay queue window!");
not the replay queue window

2021-03-01 02:17 UTC, Hubcapp commented
```
[  INFO][20:16:07] Loading resource: /assets/map/scenery.bin
java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at Client.WorldMapWindow.initScenery(Unknown Source)
	at m.a(Unknown Source)
	at client.f(Unknown Source)
	at client.a(Unknown Source)
	at e.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

2021-03-01 02:26 UTC, Hubcapp commented
Would be nice to support CTRL-A to highlight all text in the "Type to search..." box, maybe for future development.

2021-03-03 02:05 UTC, Hubcapp commented
LGTM, pending feedback from @lmsv-mx123

2021-03-03 02:06 UTC, Hubcapp commented
FUTURE TODO:
Item spawns on map
"Boundaries" aka "Wall Objects"
5x5 tiles instead of 3x3
Click objects to display info in-map
User configurable colour for highlighted search result, for colourblindness and stuff
specify labels for other floors potentially
POI on other floors
click on things to show info, including the tile
NPC heatmap

2021-03-03 02:07 UTC, Hubcapp approved these changes

2021-03-03 02:35 UTC, lmsv-mx123 commented
Looks good to me

2021-03-03 02:36 UTC, merged

2021-03-03 02:36 UTC, lmsv-mx123 approved these changes
Sweet, great job